language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t calvinyhu/docker-kubernetes-complex-client ./client -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true calvinyhu/docker-kubernetes-complex-client npm t

after_success:
  # Build production images
  - docker build -t calvinyhu/docker-kubernetes-complex-client ./client
  - docker build -t calvinyhu/docker-kubernetes-complex-nginx ./nginx
  - docker build -t calvinyhu/docker-kubernetes-complex-server ./server
  - docker build -t calvinyhu/docker-kubernetes-complex-worker ./worker
  # Log in to a Docker registry using the Docker CLI.
  # Using STDIN prevents the password from ending up in the shell’s history, or log-files.
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Push built production images to Docker hub
  - docker push calvinyhu/docker-kubernetes-complex-client
  - docker push calvinyhu/docker-kubernetes-complex-nginx
  - docker push calvinyhu/docker-kubernetes-complex-server
  - docker push calvinyhu/docker-kubernetes-complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-app
  env: docker-app-env
  bucket_name: elasticbeanstalk-us-east-1-977744602869  # S3 Bucket
  bucket_path: docker-complex-bucket
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
