version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6-alpine
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis # name of the service in this docker-compose file
      REDIS_PORT: 6379 # extracted from docker hub redis image Dockerfile
      PG_USER: postgres # default, specified in docker hub
      PG_HOST: postgres # name of the service in this docker-compose file
      PG_DATABASE: postgres # default
      PG_PASSWORD: password # no default, so set to anything
      PG_PORT: 5432 # extracted from docker hub postgres image Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
